# Generated by Django 3.1.1 on 2020-09-10 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductManagement', '0002_auto_20200910_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='file',
            field=models.FileField(blank=True, default='default.pdf', null=True, upload_to='products/files/'),
        ),
    ]
