# Generated by Django 3.1.1 on 2020-09-10 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductManagement', '0003_auto_20200910_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='file',
            field=models.FileField(blank=True, default='products/files/default.pdf', null=True, upload_to='products/files/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='products/images/default.jpg', upload_to='products/images/'),
        ),
    ]
