# Generated by Django 3.1.1 on 2020-09-11 07:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_no', models.CharField(max_length=20)),
                ('mobile_no', models.CharField(max_length=20)),
                ('pro_pic', models.ImageField(blank=True, default='users/pro_pics/default.jpg', null=True, upload_to='users/pro_pics')),
                ('portfolio_url', models.URLField(blank=True, null=True)),
                ('cv', models.FileField(blank=True, null=True, upload_to='users/cv')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
